#!/bin/bash
echo '#----------------------------------------------------------------'
echo '# Pebble SDK mod for Linux on Android'
echo '# Tested with debian distro on LinuxDeploy or UserLand'
echo '#   -Seth 16/8/2022'
echo '#----------------------------------------------------------------'
echo '# MAKE SURE TO PREPARE SYSTEM FIRST!'
echo '#----------------------------------------------------------------'
echo '# 1. Install Linux Deploy or UserLand on your Android device'
echo '# 2. Install debian linux'
echo '# 3. Run https://github.com/sethasaurus/pebble-sdk-dependencies'
echo '# 4. Run https://github.com/sethasaurus/pebble-sdk-install'
echo '# 5. Edit userdir (below), then run this script'
echo '#----------------------------------------------------------------'
#------------
# EDIT THIS:
userdir=''
#------------
if [ $userdir == '' ]
then
echo 'Error - Please edit this file and set path to your SDK install'
else
#--------------------------------------------------------------------------------------------------------
SDKDIR=/home/$userdir/pebble-dev/pebble-sdk-4.5-linux64

#--------------------------------------------------------------------------------------------------------
echo 'Finding compiler'
#--------------------------------------------------------------------------------------------------------
COMPILERVER=`arm-none-eabi-gcc --version | grep gcc | awk '{print $3}'`

#--------------------------------------------------------------------------------------------------------
echo 'Backing up stuff'
#--------------------------------------------------------------------------------------------------------
mv $SDKDIR/arm-cs-tools/arm-none-eabi $SDKDIR/arm-cs-tools/arm-none-eabi.OLD
mv $SDKDIR/arm-cs-tools/bin $SDKDIR/arm-cs-tools/bin.OLD
mv $SDKDIR/arm-cs-tools/lib $SDKDIR/arm-cs-tools/lib.OLD
mv $SDKDIR/arm-cs-tools/libexec $SDKDIR/arm-cs-tools/libexec.OLD

#--------------------------------------------------------------------------------------------------------
echo 'Creating new dirs and links'
#--------------------------------------------------------------------------------------------------------
mkdir -p $SDKDIR/arm-cs-tools/arm-none-eabi/lib
mkdir $SDKDIR/arm-cs-tools/arm-none-eabi/share
mkdir $SDKDIR/arm-cs-tools/arm-none-eabi/usr
ln -s /usr/bin $SDKDIR/arm-cs-tools/arm-none-eabi/bin
ln -s /usr/include $SDKDIR/arm-cs-tools/arm-none-eabi/include
ln -s /usr/bin $SDKDIR/arm-cs-tools/bin
mkdir -p $SDKDIR/arm-cs-tools/lib/gcc/arm-none-eabi
ln -s /usr/lib/gcc/arm-none-eabi/$COMPILERVER $SDKDIR/arm-cs-tools/lib/gcc/arm-none-eabi/4.7.2
mkdir -p $SDKDIR/arm-cs-tools/libexec/gcc/arm-none-eabi
ln -s /usr/lib/gcc/arm-none-eabi/$COMPILERVER $SDKDIR/arm-cs-tools/libexec/gcc/arm-none-eabi/4.7.2

echo '#----------------------------------------------------------------'
echo '# Arm install done!'
echo '# If no errors, you can remove any dirs with .OLD suffix'
echo '#----------------------------------------------------------------'

fi

